export const Sources = Object.freeze({
	RFS: "NSW_RFS",
	SES: "NSW_SES",
	TFNSW: "TFNSW",
	BOM: "BOM",
	OTHER: "OTHER",
});

export const SourceTypes = Object.freeze({
	FIRE: "FIRE",
	TRAFFIC: "TRAFFIC",
	WEATHER: "WEATHER",
});

export const Categories = Object.freeze({
	FIRE: "FIRE",
	TRAFFIC_INCIDENT: "TRAFFIC_INCIDENT",
	ROAD_HAZARD: "ROAD_HAZARD",
	FLOOD: "FLOOD",
	STORM: "STORM",
	WEATHER: "WEATHER",
	HAZMAT: "HAZMAT",
	RESCUE: "RESCUE",
	MEDICAL: "MEDICAL",
	PLANNED_BURN: "PLANNED_BURN",
	PUBLIC_EVENT: "PUBLIC_EVENT",
	OTHER: "OTHER",
});

export const SeverityLevels = Object.freeze({
	EMERGENCY_WARNING: "EMERGENCY_WARNING",
	WATCH_AND_ACT: "WATCH_AND_ACT",
	ADVICE: "ADVICE",
	MAJOR: "MAJOR",
	MODERATE: "MODERATE",
	MINOR: "MINOR",
	INFORMATION: "INFORMATION",
	UNKNOWN: "UNKNOWN",
});

export const Statuses = Object.freeze({
	ACTIVE: "ACTIVE",
	MONITORING: "MONITORING",
	UNDER_CONTROL: "UNDER_CONTROL",
	CONTAINED: "CONTAINED",
	CONTROLLED: "CONTROLLED",
	PLANNED: "PLANNED",
	COMPLETED: "COMPLETED",
	RESOLVED: "RESOLVED",
	CLOSED: "CLOSED",
	CANCELLED: "CANCELLED",
	UNKNOWN: "UNKNOWN",
});

export const Regions = Object.freeze({
	GREATER_SYDNEY: "GREATER_SYDNEY",
	CENTRAL_COAST: "CENTRAL_COAST",
	CENTRAL_WEST_ORANA: "CENTRAL_WEST_ORANA",
	FAR_WEST: "FAR_WEST",
	HUNTER: "HUNTER",
	ILLAWARRA_SHOALHAVEN: "ILLAWARRA_SHOALHAVEN",
	NEW_ENGLAND_NORTH_WEST: "NEW_ENGLAND_NORTH_WEST",
	NORTH_COAST: "NORTH_COAST",
	NORTHERN_RIVERS: "NORTHERN_RIVERS",
	RIVERINA: "RIVERINA",
	MURRAY_RIVERINA_REGIONAL: "MURRAY_RIVERINA_REGIONAL",
	SOUTH_EAST_TABLEANDS: "SOUTH_EAST_TABLELANDS",
	SOUTH_COAST: "SOUTH_COAST",
});

export const LGAs = Object.freeze({
	BAYSIDE: "Bayside",
	BLACKTOWN: "Blacktown",
	BLUE_MOUNTAINS: "Blue Mountains",
	BURWOOD: "Burwood",
	CAMDEN: "Camden",
	CAMPBELLTOWN: "Campbelltown",
	CANADA_BAY: "Canada Bay",
	CANTERBURY: "Canterbury",
	BANKSTOWN: "Bankstown",
	CUMBERLAND: "Cumberland",
	FAIRFIELD: "Fairfield",
	GEORGES_RIVER: "Georges River",
	HAWKESBURY: "Hawkesbury",
	HORNSBY: "Hornsby",
	HUNTERS_HILL: "Hunter's Hill",
	THE_HILLS: "The Hills Shire",
	INNER_WEST: "Inner West",
	KU_RING_GAI: "Ku-ring-gai",
	LANE_COVE: "Lane Cove",
	LIVERPOOL: "Liverpool",
	MOSMAN: "Mosman",
	NORTH_SYDNEY: "North Sydney",
	NORTHERN_BEACHES: "Northern Beaches",
	CITY_OF_PARRAMATTA: "City of Parramatta",
	PENRITH: "Penrith",
	RANDWICK: "Randwick",
	RYDE: "Ryde",
	STRATHFIELD: "Strathfield",
	SUTHERLAND_SHIRE: "Sutherland Shire",
	SYDNEY: "Sydney",
	WAVERLEY: "Waverley",
	WILLOUGHBY: "Willoughby",
	WOLLONDILLY: "Wollondilly",
	WOOLLAHRA: "Woollahra",
	SYDNEY_HARBOUR: "Sydney Harbour",
	CENTRAL_COAST: "Central Coast",
	BATHURST: "Bathurst",
	BLAYNEY: "Blayney",
	BOGAN: "Bogan",
	CABONNE: "Cabonne",
	COONAMBLE: "Coonamble",
	COWRA: "Cowra",
	DUBBO: "Dubbo",
	FORBES: "Forbes",
	GILGANDRA: "Gilgandra",
	LACHLAN: "Lachlan",
	LITHGOW: "Lithgow",
	MID_WESTERN_REGIONAL: "Mid-Western Regional",
	MID_WESTERN: "Mid-Western Regional",
	NARROMINE: "Narromine",
	OBERON: "Oberon",
	ORANGE: "Orange",
	PARKES: "Parkes",
	WARREN: "Warren",
	WARRUMBUNGLE: "Warrumbungle",
	WEDDIN: "Weddin",
	BALRANALD: "Balranald",
	BROKEN_HILL: "Broken Hill",
	CENTRAL_DARLING: "Central Darling",
	WENTWOORTH: "Wentworth",
	FAR_WEST: "Far West",
	COBAR: "Cobar",
	BOURKE: "Bourke",
	BREWARRINA: "Brewarrina",
	WALGETT: "Walgett",
	CESSNOCK: "Cessnock",
	DUNGOG: "Dungog",
	LAKE_MACQUARIE: "Lake Macquarie",
	MAITLAND: "Maitland",
	MID_COAST: "Mid-Coast",
	MUSWELLBROOK: "Muswellbrook",
	NEWCASTLE: "Newcastle",
	PORT_STEPHENS: "Port Stephens",
	SINGLETON: "Singleton",
	UPPER_HUNTER: "Upper Hunter",
	KIAMA: "Kiama",
	SHELLHARBOUR: "Shellharbour",
	SHOALHAVEN: "Shoalhaven",
	WOLLONGONG: "Wollongong",
	ARMIDALE: "Armidale",
	GLEN_INNES_SEVERN: "Glen Innes Severn",
	GUNNEDAH: "Gunnedah",
	GWYDIR: "Gwydir",
	INVERELL: "Inverell",
	LIVERPOOL_PLAINS: "Liverpool Plains",
	MOREE_PLAINS: "Moree Plains",
	NARRABRI: "Narrabri",
	TAMWORTH: "Tamworth",
	TENTERFIELD: "Tenterfield",
	URALLA: "Uralla",
	WALCHA: "Walcha",
	BELLINGEN: "Bellingen",
	COFFS_HARBOUR: "Coffs Harbour",
	KEMPSEY: "Kempsey",
	NAMBUCCA: "Nambucca",
	PORT_MACQUARIE_HASTINGS: "Port Macquarie-Hastings",
	TWEED: "Tweed",
	LORD_HOWE_ISLAND: "Lord Howe Island",
	BALLINA: "Ballina",
	BYRON: "Byron",
	CLARENCE: "Clarence",
	KYOGLE: "Kyogle",
	LISMORE: "Lismore",
	RICHMOND_VALLEY: "Richmond Valley",
	BLAND: "Bland",
	COOLAMON: "Coolamon",
	COOTAMUNDRA_GUNDAGAI: "Cootamundra-Gundagai",
	GREATER_HUME: "Greater Hume",
	JUNEE: "Junee",
	LOCKHART: "Lockhart",
	SNOWY_VALLEYS: "Snowy Valleys",
	TEMORA: "Temora",
	WAGGA_WAGGA: "Wagga Wagga",
	ALBURY: "Albury",
	BERRIGAN: "Berrigan",
	CARRATHOOL: "Carrathool",
	EDWARD_RIVER: "Edward River",
	FEDERATION: "Federation",
	GRIFFITH: "Griffith",
	HAY: "Hay",
	LEETON: "Leeton",
	MURRAY_RIVER: "Murray River",
	MURRUMBIDGEE: "Murrumbidgee",
	NARRANDERA: "Narrandera",
	GOULBURN_MULWAREE: "Goulburn Mulwaree",
	HILLTOPS: "Hilltops",
	QUEANBEYAN_PALERANG: "Queanbeyan-Palerang",
	UPPER_LACHLAN: "Upper Lachlan",
	WINGECARRIBEE: "Wingecarribee",
	YASS_VALLEY: "Yass Valley",
	SNOWY_MONARO: "Snowy Monaro Regional",
	BEGA_VALLEY: "Bega Valley",
	EUROBODALLA: "Eurobodalla",
});
