export const ContainmentStatuses = Object.freeze({
	OUT_OF_CONTROL: "OUT_OF_CONTROL",
	BEING_CONTROLLED: "BEING_CONTROLLED",
	UNDER_CONTROL: "UNDER_CONTROL",
	RESPONDING: "RESPONDING",
});

export const RFSDescriptionFields = Object.freeze({
	ALERT_LEVEL: "ALERT_LEVEL",
	LOCATION: "LOCATION",
	COUNCIL_AREA: "COUNCIL_AREA",
	STATUS: "STATUS",
	TYPE: "TYPE",
	FIRE: "FIRE",
	SIZE: "SIZE",
	RESPONSIBLE_AGENCY: "RESPONSIBLE_AGENCY",
	UPDATED: "UPDATED",
});

export const FireTypes = Object.freeze({
	FIRE: "FIRE",
	BUSH_FIRE: "BUSH_FIRE",
	BUSH_FIRE_ALERT: "BUSH_FIRE",
	GRASS_FIRE: "GRASS_FIRE",
	STRUCTURE_FIRE: "STRUCTURE_FIRE",
	HAYSTACK_FIRE: "HAYSTACK_FIRE",
	VEHICLE_EQUIPMENT_FIRE: "VEHICLE_EQUIPMENT_FIRE",
	PLANNED_BURN: "PLANNED_BURN",
	HAZARD_REDUCTION: "HAZARD_REDUCTION",
	BURN_OFF: "BURN_OFF",
});
